// Lista oficial de ativos do Bom Invest.
// Nao adicionar nem remover tickers automaticamente.

export type OfficialStock = {
  ticker: string;
  nome: string;
  setor: string;
};

export const OFFICIAL_STOCKS: OfficialStock[] = [
  { ticker: "PETR4", nome: "Petrobras PN", setor: "Petróleo e Gás" },
  { ticker: "VALE3", nome: "Vale", setor: "Mineração" },
  { ticker: "ITUB4", nome: "Itaú Unibanco PN", setor: "Bancos" },
  { ticker: "BBDC4", nome: "Bradesco PN", setor: "Bancos" },
  { ticker: "BPAC11", nome: "BTG Pactual", setor: "Bancos" },
  { ticker: "SBSP3", nome: "Sabesp", setor: "Saneamento" },
  { ticker: "BBAS3", nome: "Banco do Brasil", setor: "Bancos" },
  { ticker: "AXIA3", nome: "Axia ON", setor: "Indústria" },
  { ticker: "B3SA3", nome: "B3", setor: "Serviços Financeiros" },
  { ticker: "PETR3", nome: "Petrobras ON", setor: "Petróleo e Gás" },
  { ticker: "EMBJ3", nome: "Embraer", setor: "Indústria" },
  { ticker: "EQTL3", nome: "Equatorial Energia", setor: "Energia Elétrica" },
  { ticker: "ABEV3", nome: "Ambev", setor: "Alimentos e Bebidas" },
  { ticker: "PRIO3", nome: "PRIO", setor: "Petróleo e Gás" },
  { ticker: "UGPA3", nome: "Ultrapar", setor: "Petróleo e Gás" },
  { ticker: "VBBR3", nome: "Vibra Energia", setor: "Petróleo e Gás" },
  { ticker: "RENT3", nome: "Localiza ON", setor: "Transportes" },
  { ticker: "WEGE3", nome: "WEG", setor: "Indústria" },
  { ticker: "SUZB3", nome: "Suzano", setor: "Papel e Celulose" },
  { ticker: "ITSA4", nome: "Itaúsa PN", setor: "Holdings" },
  { ticker: "ENEV3", nome: "Eneva", setor: "Energia Elétrica" },
  { ticker: "RDOR3", nome: "Rede D'Or", setor: "Saúde" },
  { ticker: "CPLE3", nome: "Copel ON", setor: "Energia Elétrica" },
  { ticker: "CSMG3", nome: "Copasa", setor: "Saneamento" },
  { ticker: "GGBR4", nome: "Gerdau PN", setor: "Siderurgia" },
  { ticker: "BBSE3", nome: "BB Seguridade", setor: "Seguros" },
  { ticker: "MOTV3", nome: "Motiva", setor: "Transportes" },
  { ticker: "LREN3", nome: "Lojas Renner", setor: "Varejo" },
  { ticker: "ENGI11", nome: "Energisa Unit", setor: "Energia Elétrica" },
  { ticker: "CYRE3", nome: "Cyrela ON", setor: "Construção" },
  { ticker: "RAIL3", nome: "Rumo", setor: "Transportes" },
  { ticker: "CMIG4", nome: "Cemig PN", setor: "Energia Elétrica" },
  { ticker: "SMFT3", nome: "Smart Fit", setor: "Saúde" },
  { ticker: "RADL3", nome: "Raia Drogasil", setor: "Varejo" },
  { ticker: "VIVT3", nome: "Telefônica Brasil (Vivo)", setor: "Telecomunicações" },
  { ticker: "CSAN3", nome: "Cosan", setor: "Petróleo e Gás" },
  { ticker: "SANB11", nome: "Santander Brasil Unit", setor: "Bancos" },
  { ticker: "AURA33", nome: "Aura Minerals", setor: "Mineração" },
  { ticker: "TOTS3", nome: "Totvs", setor: "Tecnologia" },
  { ticker: "TIMS3", nome: "TIM Brasil", setor: "Telecomunicações" },
  { ticker: "AXIA7", nome: "Axia PN", setor: "Indústria" },
  { ticker: "MGLU3", nome: "Magazine Luiza", setor: "Varejo" },
  { ticker: "ALOS3", nome: "Allos", setor: "Varejo" },
  { ticker: "MULT3", nome: "Multiplan", setor: "Varejo" },
  { ticker: "CURY3", nome: "Cury Construtora", setor: "Construção" },
  { ticker: "EGIE3", nome: "Engie Brasil", setor: "Energia Elétrica" },
  { ticker: "GOAU4", nome: "Metalúrgica Gerdau PN", setor: "Siderurgia" },
  { ticker: "CXSE3", nome: "Caixa Seguridade", setor: "Seguros" },
  { ticker: "ASAI3", nome: "Assaí Atacadista", setor: "Varejo" },
  { ticker: "BBDC3", nome: "Bradesco ON", setor: "Bancos" },
  { ticker: "MBRF3", nome: "MBRF Global Foods", setor: "Alimentos e Bebidas" },
  { ticker: "DIRR3", nome: "Direcional", setor: "Construção" },
  { ticker: "CSNA3", nome: "CSN", setor: "Siderurgia" },
  { ticker: "TEND3", nome: "Construtora Tenda", setor: "Construção" },
  { ticker: "KLBN11", nome: "Klabin Unit", setor: "Papel e Celulose" },
  { ticker: "TAEE11", nome: "Taesa Unit", setor: "Energia Elétrica" },
  { ticker: "ISAE4", nome: "ISA Energia PN", setor: "Energia Elétrica" },
  { ticker: "FLRY3", nome: "Fleury", setor: "Saúde" },
  { ticker: "PSSA3", nome: "Porto Seguro", setor: "Seguros" },
  { ticker: "HAPV3", nome: "Hapvida", setor: "Saúde" },
  { ticker: "CEAB3", nome: "C&A Modas", setor: "Varejo" },
  { ticker: "JBSS32", nome: "JBS", setor: "Alimentos e Bebidas" },
  { ticker: "ITUB3", nome: "Itaú Unibanco ON", setor: "Bancos" },
  { ticker: "BRAV3", nome: "Brava Energia", setor: "Petróleo e Gás" },
  { ticker: "BEEF3", nome: "Minerva Foods", setor: "Alimentos e Bebidas" },
  { ticker: "CPFE3", nome: "CPFL Energia", setor: "Energia Elétrica" },
  { ticker: "SAUD3", nome: "Kora Saúde", setor: "Saúde" },
  { ticker: "MRVE3", nome: "MRV Engenharia", setor: "Construção" },
  { ticker: "USIM5", nome: "Usiminas PNA", setor: "Siderurgia" },
  { ticker: "HYPE3", nome: "Hypera Pharma", setor: "Saúde" },
  { ticker: "COGN3", nome: "Cogna Educação", setor: "Educação" },
  { ticker: "IGTI11", nome: "Iguatemi Unit", setor: "Varejo" },
  { ticker: "NATU3", nome: "Natura &Co", setor: "Varejo" },
  { ticker: "POMO4", nome: "Marcopolo PN", setor: "Indústria" },
  { ticker: "VIVA3", nome: "Vivara", setor: "Varejo" },
  { ticker: "SLCE3", nome: "SLC Agrícola", setor: "Agronegócio" },
  { ticker: "VAMO3", nome: "Vamos", setor: "Transportes" },
  { ticker: "ONCO3", nome: "Oncoclínicas", setor: "Saúde" },
  { ticker: "SAPR11", nome: "Sanepar Unit", setor: "Saneamento" },
  { ticker: "AZZA3", nome: "Azzas 2154", setor: "Varejo" },
  { ticker: "EZTC3", nome: "EZTEC", setor: "Construção" },
  { ticker: "SMTO3", nome: "São Martinho", setor: "Agronegócio" },
  { ticker: "GGPS3", nome: "GPS Participações", setor: "Serviços" },
  { ticker: "IRBR3", nome: "IRB Brasil RE", setor: "Seguros" },
  { ticker: "BRKM5", nome: "Braskem PNA", setor: "Química" },
  { ticker: "YDUQ3", nome: "YDUQS", setor: "Educação" },
  { ticker: "JHSF3", nome: "JHSF Participações", setor: "Construção" },
  { ticker: "CMIN3", nome: "CSN Mineração", setor: "Mineração" },
  { ticker: "MOVI3", nome: "Movida", setor: "Transportes" },
  { ticker: "ECOR3", nome: "EcoRodovias", setor: "Transportes" },
  { ticker: "ORVR3", nome: "Orizon", setor: "Serviços" },
  { ticker: "BRAP4", nome: "Bradespar PN", setor: "Holdings" },
  { ticker: "PASS3", nome: "Pass Participações", setor: "Serviços" },
  { ticker: "ALUP11", nome: "Alupar Unit", setor: "Energia Elétrica" },
  { ticker: "AURE3", nome: "Auren Energia", setor: "Energia Elétrica" },
  { ticker: "ALPA4", nome: "Alpargatas PN", setor: "Varejo" },
  { ticker: "GMAT3", nome: "Grupo Mateus", setor: "Varejo" },
  { ticker: "VULC3", nome: "Vulcabras", setor: "Varejo" },
  { ticker: "MDNE3", nome: "Moura Dubeux", setor: "Construção" },
  { ticker: "CBAV3", nome: "CBA - Cia Brasileira de Alumínio", setor: "Mineração" },
  { ticker: "RECV3", nome: "PetroReconcavo", setor: "Petróleo e Gás" },
  { ticker: "ANIM3", nome: "Ânima Educação", setor: "Educação" },
  { ticker: "CVCB3", nome: "CVC Brasil", setor: "Serviços" },
  { ticker: "TTEN3", nome: "3tentos", setor: "Agronegócio" },
  { ticker: "SBFG3", nome: "Grupo SBF", setor: "Varejo" },
  { ticker: "SIMH3", nome: "Simpar", setor: "Transportes" },
  { ticker: "SEER3", nome: "Ser Educacional", setor: "Educação" },
  { ticker: "UNIP6", nome: "Unipar PNB", setor: "Química" },
  { ticker: "AUAU3", nome: "Auau Participações", setor: "Serviços" },
  { ticker: "INTB3", nome: "Intelbras", setor: "Tecnologia" },
  { ticker: "LWSA3", nome: "Locaweb", setor: "Tecnologia" },
  { ticker: "BRSR6", nome: "Banrisul PNB", setor: "Bancos" },
  { ticker: "PGMN3", nome: "Pague Menos", setor: "Varejo" },
  { ticker: "GRND3", nome: "Grendene", setor: "Varejo" },
  { ticker: "MDIA3", nome: "M. Dias Branco", setor: "Alimentos e Bebidas" },
  { ticker: "LIGT3", nome: "Light", setor: "Energia Elétrica" },
  { ticker: "PCAR3", nome: "Grupo Pão de Açúcar", setor: "Varejo" },
  { ticker: "BMOB3", nome: "Bemobi", setor: "Tecnologia" },
  { ticker: "PINE4", nome: "Banco Pine PN", setor: "Bancos" },
  { ticker: "ABCB4", nome: "Banco ABC Brasil PN", setor: "Bancos" },
  { ticker: "KLBN4", nome: "Klabin PN", setor: "Papel e Celulose" },
  { ticker: "RAPT4", nome: "Randon PN", setor: "Indústria" },
  { ticker: "RIAA3", nome: "Riaa Participações", setor: "Serviços" },
  { ticker: "AZEV3", nome: "Azevedo & Travassos ON", setor: "Petróleo e Gás" },
  { ticker: "DESK3", nome: "Desktop", setor: "Telecomunicações" },
  { ticker: "PLPL3", nome: "Plano & Plano", setor: "Construção" },
  { ticker: "LOGG3", nome: "LOG Commercial Properties", setor: "Construção" },
  { ticker: "VTRU3", nome: "Vitru Educação", setor: "Educação" },
  { ticker: "DXCO3", nome: "Dexco", setor: "Indústria" },
  { ticker: "AZEV4", nome: "Azevedo & Travassos PN", setor: "Petróleo e Gás" },
  { ticker: "FESA4", nome: "Ferbasa PN", setor: "Siderurgia" },
  { ticker: "CASH3", nome: "Méliuz", setor: "Tecnologia" },
  { ticker: "TGMA3", nome: "Tegma", setor: "Transportes" },
  { ticker: "PRNR3", nome: "Priner", setor: "Serviços" },
  { ticker: "SAPR4", nome: "Sanepar PN", setor: "Saneamento" },
  { ticker: "TFCO4", nome: "Track & Field PN", setor: "Varejo" },
  { ticker: "CYRE4", nome: "Cyrela PN", setor: "Construção" },
  { ticker: "TUPY3", nome: "Tupy", setor: "Indústria" },
  { ticker: "OPCT3", nome: "OceanPact", setor: "Serviços" },
  { ticker: "PNVL3", nome: "Grupo Dimed (Panvel)", setor: "Varejo" },
  { ticker: "LEVE3", nome: "Mahle Metal Leve", setor: "Indústria" },
  { ticker: "MILS3", nome: "Mills", setor: "Serviços" },
  { ticker: "KEPL3", nome: "Kepler Weber", setor: "Indústria" },
  { ticker: "OBTC3", nome: "OBTC Participações", setor: "Serviços" },
  { ticker: "BHIA3", nome: "Casas Bahia", setor: "Varejo" },
  { ticker: "POMO3", nome: "Marcopolo ON", setor: "Indústria" },
  { ticker: "AMER3", nome: "Americanas", setor: "Varejo" },
  { ticker: "BMGB4", nome: "Banco BMG PN", setor: "Bancos" },
  { ticker: "MYPK3", nome: "Iochpe-Maxion", setor: "Indústria" },
  { ticker: "USIM3", nome: "Usiminas ON", setor: "Siderurgia" },
  { ticker: "SOJA3", nome: "Boa Safra Sementes", setor: "Agronegócio" },
  { ticker: "RENT4", nome: "Localiza PN", setor: "Transportes" },
  { ticker: "LAVV3", nome: "Lavvi Incorporadora", setor: "Construção" },
  { ticker: "HBSA3", nome: "Hidrovias do Brasil", setor: "Transportes" },
  { ticker: "QUAL3", nome: "Qualicorp", setor: "Saúde" },
  { ticker: "JSLG3", nome: "JSL", setor: "Transportes" },
  { ticker: "EVEN3", nome: "Even Construtora", setor: "Construção" },
  { ticker: "FIQE3", nome: "Unifique", setor: "Telecomunicações" },
  { ticker: "RANI3", nome: "Irani Papel e Embalagem", setor: "Papel e Celulose" },
  { ticker: "SANB4", nome: "Santander Brasil PN", setor: "Bancos" },
  { ticker: "BRBI11", nome: "BR Partners Unit", setor: "Bancos" },
  { ticker: "SANB3", nome: "Santander Brasil ON", setor: "Bancos" },
  { ticker: "MLAS3", nome: "Multilaser (Mult Ass)", setor: "Tecnologia" },
  { ticker: "FRAS3", nome: "Fras-le", setor: "Indústria" },
  { ticker: "VLID3", nome: "Valid", setor: "Tecnologia" },
  { ticker: "ARML3", nome: "Armac", setor: "Serviços" },
  { ticker: "CAML3", nome: "Camil Alimentos", setor: "Alimentos e Bebidas" },
  { ticker: "RAIZ4", nome: "Raízen PN", setor: "Petróleo e Gás" },
  { ticker: "TAEE4", nome: "Taesa PN", setor: "Energia Elétrica" },
  { ticker: "RCSL4", nome: "Recrusul PN", setor: "Indústria" },
  { ticker: "JALL3", nome: "Jalles Machado", setor: "Agronegócio" },
  { ticker: "POSI3", nome: "Positivo Tecnologia", setor: "Tecnologia" },
  { ticker: "ALLD3", nome: "Allied Tecnologia", setor: "Tecnologia" },
  { ticker: "DASA3", nome: "Dasa", setor: "Saúde" },
  { ticker: "KLBN3", nome: "Klabin ON", setor: "Papel e Celulose" },
  { ticker: "AGRO3", nome: "BrasilAgro", setor: "Agronegócio" },
  { ticker: "WIZC3", nome: "Wiz Co", setor: "Seguros" },
  { ticker: "LJQQ3", nome: "Lojas Quero-Quero", setor: "Varejo" },
  { ticker: "PMAM3", nome: "Paranapanema", setor: "Indústria" },
  { ticker: "BLAU3", nome: "Blau Farmacêutica", setor: "Saúde" },
  { ticker: "AZTE3", nome: "AZT Energia", setor: "Petróleo e Gás" },
  { ticker: "CMIG3", nome: "Cemig ON", setor: "Energia Elétrica" },
  { ticker: "MTRE3", nome: "Mitre Realty", setor: "Construção" },
  { ticker: "TASA4", nome: "Taurus Armas PN", setor: "Indústria" },
  { ticker: "SHUL4", nome: "Schulz PN", setor: "Indústria" },
  { ticker: "BMEB4", nome: "Banco Mercantil do Brasil PN", setor: "Bancos" },
  { ticker: "AZUL3", nome: "Azul", setor: "Transportes" },
  { ticker: "ITSA3", nome: "Itaúsa ON", setor: "Holdings" },
  { ticker: "TAEE3", nome: "Taesa ON", setor: "Energia Elétrica" },
  { ticker: "EUCA4", nome: "Eucatex PN", setor: "Indústria" },
  { ticker: "HBRE3", nome: "HBR Realty", setor: "Construção" },
  { ticker: "SYNE3", nome: "SYN Prop e Tech", setor: "Construção" },
  { ticker: "CSED3", nome: "Cruzeiro do Sul Educacional", setor: "Educação" },
  { ticker: "TRIS3", nome: "Trisul", setor: "Construção" },
  { ticker: "MELK3", nome: "Melnick", setor: "Construção" },
  { ticker: "DOTZ3", nome: "Dotz", setor: "Tecnologia" },
  { ticker: "HBOR3", nome: "Helbor", setor: "Construção" },
  { ticker: "PTBL3", nome: "Portobello", setor: "Indústria" },
  { ticker: "PFRM3", nome: "Profarma", setor: "Saúde" },
  { ticker: "SAPR3", nome: "Sanepar ON", setor: "Saneamento" },
  { ticker: "ROMI3", nome: "Indústrias Romi", setor: "Indústria" },
  { ticker: "MATD3", nome: "Mater Dei", setor: "Saúde" },
  { ticker: "VITT3", nome: "Vittia", setor: "Agronegócio" },
  { ticker: "TECN3", nome: "Technos", setor: "Varejo" },
  { ticker: "CLSC4", nome: "Celesc PN", setor: "Energia Elétrica" },
  { ticker: "VVEO3", nome: "Viveo", setor: "Saúde" },
  { ticker: "ENJU3", nome: "Enjoei", setor: "Varejo" },
  { ticker: "ESPA3", nome: "Espaçolaser", setor: "Serviços" },
  { ticker: "AMBP3", nome: "Ambipar", setor: "Serviços" },
  { ticker: "CSUD3", nome: "CSU Digital", setor: "Tecnologia" },
  { ticker: "RAPT3", nome: "Randon ON", setor: "Indústria" },
  { ticker: "ALPK3", nome: "Estapar (Allpark)", setor: "Serviços" },
  { ticker: "BRST3", nome: "Brisanet", setor: "Telecomunicações" },
  { ticker: "GGBR3", nome: "Gerdau ON", setor: "Siderurgia" },
  { ticker: "BRAP3", nome: "Bradespar ON", setor: "Holdings" },
  { ticker: "GFSA3", nome: "Gafisa", setor: "Construção" },
  { ticker: "DEXP3", nome: "Dexxos Participações", setor: "Química" },
];

export const SECTORS = Array.from(
  new Set(OFFICIAL_STOCKS.map((s) => s.setor)),
).sort((a, b) => a.localeCompare(b, "pt-BR"));

export function getYahooSymbol(ticker: string): string {
  return `${ticker.trim().toUpperCase()}.SA`;
}
